---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: linux
  gather_facts: True
 
  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port, dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port | default ('none')}}"

    - name: Test hostvars with an ansible fact and collect ansible_port, dict notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] | default('none') }}"
    
    
    # accessing a group var : method1
    - name : Showing the ansible_become_pass of ubuntu hosts 
      debug:
        msg: "{{ hostvars[item]['ansible_become_pass'] }}"
      with_items: "{{groups['ubuntu']}}"
      when: ansible_distribution == "Ubuntu"
    # accessing a group var : method2 
    # - name : Showing the ansible_become_pass of ubuntu hosts 
    #   debug:
    #     msg: "{{ hostvars[groups['ubuntu'].0]['ansible_become_pass'] }}"
    #   when: ansible_distribution == "Ubuntu"
        
# Three dots indicate the end of a YAML document
...
